name: Metrics Collector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag metrics-collector:$(date +%s)
